/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedExtensionConnectRouteImport } from './routes/_authenticated/extension-connect'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicExtensionSyncItemsRouteImport } from './routes/api/public/extension/sync-items'
import { Route as AuthenticatedAccountsAccountIdItemsRouteImport } from './routes/_authenticated/accounts.$accountId.items'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExtensionConnectRoute =
  AuthenticatedExtensionConnectRouteImport.update({
    id: '/extension-connect',
    path: '/extension-connect',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicExtensionSyncItemsRoute =
  ApiPublicExtensionSyncItemsRouteImport.update({
    id: '/api/public/extension/sync-items',
    path: '/api/public/extension/sync-items',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountsAccountIdItemsRoute =
  AuthenticatedAccountsAccountIdItemsRouteImport.update({
    id: '/accounts/$accountId/items',
    path: '/accounts/$accountId/items',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extension-connect': typeof AuthenticatedExtensionConnectRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/$accountId/items': typeof AuthenticatedAccountsAccountIdItemsRoute
  '/api/public/extension/sync-items': typeof ApiPublicExtensionSyncItemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extension-connect': typeof AuthenticatedExtensionConnectRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/accounts/$accountId/items': typeof AuthenticatedAccountsAccountIdItemsRoute
  '/api/public/extension/sync-items': typeof ApiPublicExtensionSyncItemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/extension-connect': typeof AuthenticatedExtensionConnectRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/accounts/$accountId/items': typeof AuthenticatedAccountsAccountIdItemsRoute
  '/api/public/extension/sync-items': typeof ApiPublicExtensionSyncItemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/extension-connect'
    | '/settings'
    | '/accounts/$accountId/items'
    | '/api/public/extension/sync-items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/extension-connect'
    | '/settings'
    | '/accounts/$accountId/items'
    | '/api/public/extension/sync-items'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/extension-connect'
    | '/_authenticated/settings'
    | '/_authenticated/accounts/$accountId/items'
    | '/api/public/extension/sync-items'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicExtensionSyncItemsRoute: typeof ApiPublicExtensionSyncItemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extension-connect': {
      id: '/_authenticated/extension-connect'
      path: '/extension-connect'
      fullPath: '/extension-connect'
      preLoaderRoute: typeof AuthenticatedExtensionConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/extension/sync-items': {
      id: '/api/public/extension/sync-items'
      path: '/api/public/extension/sync-items'
      fullPath: '/api/public/extension/sync-items'
      preLoaderRoute: typeof ApiPublicExtensionSyncItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts/$accountId/items': {
      id: '/_authenticated/accounts/$accountId/items'
      path: '/accounts/$accountId/items'
      fullPath: '/accounts/$accountId/items'
      preLoaderRoute: typeof AuthenticatedAccountsAccountIdItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExtensionConnectRoute: typeof AuthenticatedExtensionConnectRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAccountsAccountIdItemsRoute: typeof AuthenticatedAccountsAccountIdItemsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExtensionConnectRoute: AuthenticatedExtensionConnectRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAccountsAccountIdItemsRoute:
    AuthenticatedAccountsAccountIdItemsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicExtensionSyncItemsRoute: ApiPublicExtensionSyncItemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
